- hosts: all
  become: yes
  tasks: 
  - name: Install httpd
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Start service httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes

  - name: Add the users
    ansible.builtin.user:
      name: "{{ item }}"
    loop:
      - jenny
      - rose
      - jisoo
      - lisa
